<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class C_laporanperbaikan extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('M_laporanperbaikan');
        $this->load->model('M_pengajuanperbaikan');
        $this->load->model('M_user');
        $this->load->model('M_notifpengajuan');
        $this->load->library('session');

        if ($this->session->userdata('username')) {
        } else {
            redirect('C_User');
        }
    }

    /*
     * Listing of laporanperbaikan
     */
    public function index()
    {
        if ($this->session->userdata('tipe_user')=='Admin') {
            $data['pengajuan'] = $this->M_pengajuanperbaikan->get_pengajuan_all();
            $data['laporan'] =   $this->M_laporanperbaikan->get_laporan_all();
            $data['_view'] = 'laporan/admin';
            $this->load->view('layouts/main', $data);
        } else {
            $data['pengajuan'] = $this->M_pengajuanperbaikan->get_pengajuan_ByUser($this->session->userdata('id_user'));
            $data['laporan'] = $this->M_laporanperbaikan->get_laporan_ByUser($this->session->userdata('id_user'));
            $data['_view'] = 'laporan/teknisi';
            $this->load->view('layouts/main', $data);
        }
    }

    public function close_pengajuan($id_pengajuan)
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params2[]= array(
            'id_pengajuan' => $id_pengajuan,
            'id_user' => 1,
            'StatusNotif' => 'No'
          );
            $this->session->set_flashdata('msg-update', 'berhasil');
            $notifpengajuan_id = $this->M_notifpengajuan->add_notifpengajuan($params2);
            redirect('C_laporanperbaikan/index');
        } else {
            $data["url_close"] = base_url()."C_laporanperbaikan/close_pengajuan/".$this->input->get('id_delete');
            $data["id_delete"] = $this->input->get('id_delete');
            $this->load->view('layouts/close', $data);
        }
    }


    /*
     * Adding a new laporanperbaikan
     */
    public function add($id_pengajuan)
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_user' => $this->session->userdata('id_user'),
                'id_pengajuan' => $id_pengajuan,
                'jenisPerbaikan' => $this->input->post('jenisPerbaikan'),
                'laporan' => $this->input->post('laporan'),
                'Solusi' => $this->input->post('Solusi'),
                'Waktu' => $this->input->post('waktu')
            );
            $status = array(
                'id_status' => 2
            );
            $laporanperbaikan_id = $this->M_laporanperbaikan->add_laporanperbaikan($params);
            $pengajuan_status = $this->M_pengajuanperbaikan->update_pengajuanperbaikan($id_pengajuan, $status);
            $this->session->set_flashdata('msg-insert', 'berhasil');
            redirect('c_laporanperbaikan/index');
        } else {
            $data['pengajuanperbaikan'] = $this->M_pengajuanperbaikan->get_pengajuanperbaikan($id_pengajuan);
            $data['all_teknisi'] = $this->M_notifpengajuan->get_notifpengajuan_byPengajuan($id_pengajuan);

            $this->load->view('laporan/add', $data);
        }
    }

    /*
     * Editing a laporanperbaikan
     */
    public function edit($id_laporan)
    {
        // check if the laporanperbaikan exists before trying to edit it
        $data['laporanperbaikan'] = $this->M_laporanperbaikan->get_laporanperbaikan($id_laporan);

        if (isset($data['laporanperbaikan']['id_laporan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'jenisPerbaikan' => $this->input->post('jenisPerbaikan'),
                    'laporan' => $this->input->post('laporan'),
                    'Solusi' => $this->input->post('Solusi'),
                    'waktu' => $this->input->post('tanggal').' '.$this->input->post('jam'),
                );

                $this->M_laporanperbaikan->update_laporanperbaikan($id_laporan, $params);
                $this->session->set_flashdata('msg-update', 'berhasil');
                redirect('c_laporanperbaikan/index');
            } else {
                $data['all_user'] = $this->M_user->get_all_user();
                $this->load->view('laporan/edit', $data);
                // $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The laporanperbaikan you are trying to edit does not exist.');
        }
    }

    /*
     * Deleting laporanperbaikan
     */
    public function remove($id_laporan)
    {
        if (isset($_POST) && count($_POST) > 0) {
            $laporanperbaikan = $this->M_laporanperbaikan->get_laporanperbaikan($id_laporan);

            // check if the laporanperbaikan exists before trying to delete it
            if (isset($laporanperbaikan['id_laporan'])) {
                $this->M_laporanperbaikan->delete_laporanperbaikan($id_laporan);
                $this->session->set_flashdata('msg-del', 'berhasil');
                redirect('c_laporanperbaikan/index');
            } else {
                show_error('The laporanperbaikan you are trying to delete does not exist.');
            }
        } else {
            $data["url_del"] = base_url()."C_laporanperbaikan/remove/".$this->input->get('id_delete');
            $data["id_delete"] = $this->input->get('id_delete');
            $this->load->view('layouts/delete', $data);
        }
    }

    // public function v_deletelaporan()
    // {
    //     $data["url_del"] = base_url()."C_laporanperbaikan/remove/".$this->input->post('id_delete');
    //     $data["id_delete"] = $this->input->get('id_delete');
    //     $this->load->view('layouts/delete', $data);
    // }
}
