<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class C_unitkerja extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('M_unitkerja');
        $this->load->library('session');

        if ($this->session->userdata('username')) {
        } else {
            redirect('C_User');
        }
    }

    /*
     * Listing of unitkerja
     */
    public function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('unitkerja/index?');
        $config['total_rows'] = $this->M_unitkerja->get_all_unitkerja_count();
        $this->pagination->initialize($config);

        $data['unitkerja'] = $this->M_unitkerja->get_all_unitkerja($params);

        $data['_view'] = 'unitkerja/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new unitkerja
     */
    public function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'namaUnit' => $this->input->post('namaUnit'),
            );

            $unitkerja_id = $this->M_unitkerja->add_unitkerja($params);
            redirect('c_unitkerja/index');
        } else {
            $data['_view'] = 'unitkerja/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a unitkerja
     */
    public function edit($id_unitKerja)
    {
        // check if the unitkerja exists before trying to edit it
        $data['unitkerja'] = $this->M_unitkerja->get_unitkerja($id_unitKerja);

        if (isset($data['unitkerja']['id_unitKerja'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'namaUnit' => $this->input->post('namaUnit'),
                );

                $this->M_unitkerja->update_unitkerja($id_unitKerja, $params);
                redirect('c_unitkerja/index');
            } else {
                $data['_view'] = 'unitkerja/edit';
                $this->load->view('layouts/main', $data);
            }
        } else {
            show_error('The unitkerja you are trying to edit does not exist.');
        }
    }

    /*
     * Deleting unitkerja
     */
    public function remove($id_unitKerja)
    {
        $unitkerja = $this->M_unitkerja->get_unitkerja($id_unitKerja);

        // check if the unitkerja exists before trying to delete it
        if (isset($unitkerja['id_unitKerja'])) {
            $this->M_unitkerja->delete_unitkerja($id_unitKerja);
            redirect('c_unitkerja/index');
        } else {
            show_error('The unitkerja you are trying to delete does not exist.');
        }
    }
}
