<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_notifpengajuan extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    public function get_teknisi($id_pengajuan)
    {
        $this->db->select('not.id_notif, not.id_user, us.username, p.id_pengajuan');
        $this->db->from('notifpengajuan not');
        $this->db->join('pengajuanperbaikan p', 'p.id_pengajuan = not.id_pengajuan');
        $this->db->join('user us', 'us.id_user = not.id_user');
        $this->db->where('p.id_pengajuan', $id_pengajuan);
        $this->db->where('not.id_user !=', 1);
        return $this->db->get()->result_array();
    }

    public function get_notifpengajuan_byUser($id_user)
    {
        $this->db->select('notif.id_notif, p.id_pengajuan, p.permasalahan as Permasalahan, uk.namaUnit as UnitKerja');
        $this->db->from('notifpengajuan notif');
        $this->db->join('user', 'user.id_user = notif.id_user');
        $this->db->join('pengajuanperbaikan p', 'notif.id_pengajuan = p.id_pengajuan');
        $this->db->join('unitKerja uk', 'uk.id_unitKerja = p.id_unitKerja');
        $this->db->where('notif.id_user', $id_user);
        $this->db->order_by('notif.id_notif', 'desc');
        return $this->db->get();
    }

    public function get_jumNotif_ByUser($id_user)
    {
        $this->db->from('notifpengajuan');
        $this->db->where('id_user', $id_user);
        $this->db->where('StatusNotif', 'No');
        return $this->db->count_all_results();
    }

    public function add_notifpengajuan($params)
    {
        $this->db->insert_batch('notifpengajuan', $params);
        return $this->db->insert_id();
    }

    public function edit_notifpengajuan($params)
    {
        return $this->db->update_batch('notifpengajuan', $params, 'id_notif');
    }

    public function get_notifuser_byPengajuan($id_pengajuan)
    {
        $this->db->select('notif.id_notif, notif.id_user, user.username, user.id_user as user_id_user, notif.id_pengajuan');
        $this->db->from('notifpengajuan notif');
        $this->db->join('user', 'user.id_user = notif.id_user');
        $this->db->where('notif.id_pengajuan', $id_pengajuan);
        return $this->db->get()->row_array();
    }

    public function get_notifpengajuan_byPengajuan($id_pengajuan)
    {
        $this->db->select('notif.id_notif, notif.id_user, user.username, user.id_user as user_id_user, notif.id_pengajuan');
        $this->db->from('notifpengajuan notif');
        $this->db->join('user', 'user.id_user = notif.id_user');
        $this->db->where('notif.id_pengajuan', $id_pengajuan);
        return $this->db->get()->result_array();
    }

    public function get_teknisidetail_byStatus()
    {
        $this->db->select('notif.id_user, us.username, us.Bidang, sum(case when peng.id_status = 1 then 1 else 0 end) as baru, sum(case when peng.id_status = 2 then 1 else 0 end) as sedang, sum(case when peng.id_status = 3 then 1 else 0 end) as selesai');
        $this->db->from('notifpengajuan notif');
        $this->db->join('pengajuanperbaikan peng', 'notif.id_pengajuan = peng.id_pengajuan');
        $this->db->join('user us', 'us.id_user = notif.id_user');
        $this->db->group_by('notif.id_user, us.username');
        $this->db->where('us.id_user !=', 1);
        return $this->db->get()->result_array();
    }

    public function delete_notifikasi_byPengajuan($id_pengajuan)
    {
        return $this->db->delete('notifpengajuan', array('id_pengajuan'=>$id_pengajuan));        
    }

    public function delete_teknisi($id_notif)
    {
        return $this->db->delete('notifpengajuan', array('id_notif'=>$id_notif));
    }

    public function get_notif($id_notif)
    {
        $this->db->select('id_notif, id_pengajuan');
        $this->db->from('notifpengajuan');
        $this->db->where('id_notif', $id_notif);
        return $this->db->get()->row_array();
    }

    public function update_notif($params, $id_user)
    {
        $this->db->where('id_user', $id_user);
        return $this->db->update('notifpengajuan', $params);
    }
}
