<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_pengajuanperbaikan extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    public function get_pengajuanperbaikan($id_pengajuan)
    {
        $this->db->select('pengajuanperbaikan.id_pengajuan, pengajuanperbaikan.id_unitKerja, unitKerja.namaUnit, date(pengajuanperbaikan.waktu) as tanggal, DATE_FORMAT(pengajuanperbaikan.waktu, "%h:%i") as jam, pengajuanperbaikan.waktu as waktu, pengajuanperbaikan.permasalahan, pengajuanperbaikan.id_status, status.status, user.username');
        $this->db->from('pengajuanperbaikan');
        $this->db->join('unitKerja', 'unitKerja.id_unitKerja = pengajuanperbaikan.id_unitKerja');
        $this->db->join('status', 'status.id_status = pengajuanperbaikan.id_status');
        $this->db->join('user', 'user.id_user = pengajuanperbaikan.id_user');
        $this->db->where('id_pengajuan', $id_pengajuan);
        return $this->db->get()->row_array();
    }

    public function get_detailpengajuan($id_pengajuan)
    {
        $this->db->select('pengajuanperbaikan.id_pengajuan, pengajuanperbaikan.id_unitKerja, unitKerja.namaUnit, date(pengajuanperbaikan.waktu) as tanggal, DATE_FORMAT(pengajuanperbaikan.waktu, "%h:%i") as jam, pengajuanperbaikan.waktu as waktu, pengajuanperbaikan.permasalahan, pengajuanperbaikan.id_status, status.status');
        $this->db->from('pengajuanperbaikan');
        $this->db->join('unitKerja', 'unitKerja.id_unitKerja = pengajuanperbaikan.id_unitKerja');
        $this->db->join('status', 'status.id_status = pengajuanperbaikan.id_status');
        $this->db->where('id_pengajuan', $id_pengajuan);
        return $this->db->get();
    }

    public function get_pengajuan_all()
    {
        $this->db->select('p.id_pengajuan as id_pengajuan, un.namaUnit as UnitKerja, p.permasalahan as Permasalahan, p.waktu as Waktu, us.username as Username,  s.status as Status, s.id_status');
        $this->db->from('pengajuanperbaikan p');
        $this->db->join('unitKerja un', 'p.id_unitKerja = un.id_unitKerja');
        $this->db->join('user us', 'p.id_user = us.id_user');
        $this->db->join('status s', 'p.id_status = s.id_status');
        $this->db->order_by('p.id_pengajuan', 'desc');
        return $this->db->get()->result_array();
    }

    // public function get_teknisipengajuan($id_pengajuan)
    // {
    //     $this->db->select('not.id_notif, not.id_user, us.username, p.id_pengajuan');
    //     $this->db->from('notifpengajuan not');
    //     $this->db->join('pengajuanperbaikan p', 'p.id_pengajuan = not.id_pengajuan');
    //     $this->db->join('user us', 'us.id_user = not.id_user');
    //     $this->db->where('p.id_pengajuan', $id_pengajuan);
    //     $this->db->where('not.id_user !=', 1);
    //     return $this->db->get();
    // }

    public function get_pencarian_ByUnitKerja($id_unitKerja)
    {
        $this->db->select('pengajuanperbaikan.id_pengajuan as id_pengajuan, unitKerja.namaUnit as UnitKerja, pengajuanperbaikan.permasalahan as Permasalahan, pengajuanperbaikan.waktu as Waktu , status.status as Status, status.id_status ');
        $this->db->from('pengajuanperbaikan');
        $this->db->join('unitKerja', 'unitKerja.id_unitKerja = pengajuanperbaikan.id_unitKerja');
        $this->db->join('status', 'status.id_status = pengajuanperbaikan.id_status');
        $this->db->where('pengajuanperbaikan.id_unitKerja', $id_unitKerja);
        $this->db->order_by('pengajuanperbaikan.id_pengajuan', 'desc');
        return $this->db->get();
    }

    public function get_all_unitkerja()
    {
        $this->db->order_by('id_unitKerja', 'desc');
        return $this->db->get('unitkerja')->result_array();
    }

    public function get_all_status()
    {
        $this->db->order_by('id_status', 'desc');
        return $this->db->get('status')->result_array();
    }

    public function get_jumpengajuan_byStatus($id_status)
    {
        $this->db->from('pengajuanperbaikan');
        $this->db->where('id_status', $id_status);
        return $this->db->count_all_results();
    }

    public function get_detailpengajuan_byPengajuan($id_pengajuan)
    {
        $this->db->select('l.id_laporan, l.id_pengajuan, l.laporan, p.permasalahan, uk.namaUnit, us.username, l.jenisPerbaikan, s.status, p.waktu as waktup, l.waktu as waktul, l.solusi');
        $this->db->from('laporanperbaikan l');
        $this->db->join('pengajuanperbaikan p', 'p.id_pengajuan = l.id_pengajuan');
        $this->db->join('unitKerja uk', 'uk.id_unitKerja = p.id_unitKerja');
        $this->db->join('status s', 's.id_status = p.id_status');
        $this->db->join('user us', 'us.id_user = l.id_user');
        $this->db->where('l.id_pengajuan', $id_pengajuan);
        $this->db->order_by('l.id_laporan', 'desc');
        return $this->db->get();
    }

    public function get_pengajuan_ByUser($iduser)
    {
        $this->db->select('notif.id_notif, p.id_pengajuan, un.namaUnit as UnitKerja, p.permasalahan as Permasalahan, us.username as Username, p.waktu as Waktu, s.status as Status, s.id_status');
        $this->db->from('pengajuanperbaikan p');
        $this->db->join('unitKerja un', 'p.id_unitKerja = un.id_unitKerja');
        $this->db->join('user us', 'p.id_user = us.id_user');
        $this->db->join('status s', 'p.id_status = s.id_status');
        $this->db->join('notifpengajuan notif', 'p.id_pengajuan = notif.id_pengajuan');
        $this->db->where('notif.id_user', $iduser);
        $this->db->order_by('p.id_pengajuan', 'desc');
        return $this->db->get()->result_array();
    }

    // grafik pengajuan per bulann
    public function get_jumpengajuan_byMonth()
    {
        $this->db->select('DATE_FORMAT(waktu, "%M") as bulan,count(*) as jumlah');
        $this->db->from('pengajuanperbaikan');
        $this->db->where('year(waktu)', '2018');
        $this->db->group_by('month(waktu)');
        return $this->db->get();
    }

    //grafik pengajuan per unit
    public function get_pengajuan_all_unit()
    {
        $this->db->select('uk.id_unitKerja, uk.namaUnit, count(*) total');
        $this->db->from('pengajuanperbaikan');
        $this->db->join('unitKerja uk', 'uk.id_unitKerja = pengajuanperbaikan.id_unitKerja');
        $this->db->group_by('uk.id_unitKerja, uk.namaUnit');
        return $this->db->get();
    }

    public function add_pengajuanperbaikan($params)
    {
        $this->db->insert('pengajuanperbaikan', $params);
        return $this->db->insert_id();
    }

    public function update_pengajuanperbaikan($id_pengajuan, $params)
    {
        $this->db->where('id_pengajuan', $id_pengajuan);
        return $this->db->update('pengajuanperbaikan', $params);
    }

    public function delete_pengajuanperbaikan($id_pengajuan)
    {
        return $this->db->delete('pengajuanperbaikan', array('id_pengajuan'=>$id_pengajuan));
    }
}
