<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class M_status extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get status by id_status
     */
    function get_status($id_status)
    {
        return $this->db->get_where('status',array('id_status'=>$id_status))->row_array();
    }
    
    /*
     * Get all statuss count
     */
    function get_all_statuss_count()
    {
        $this->db->from('status');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all statuss
     */
    function get_all_statuss($params = array())
    {
        $this->db->order_by('id_status', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('status')->result_array();
    }
        
    /*
     * function to add new status
     */
    function add_status($params)
    {
        $this->db->insert('status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update status
     */
    function update_status($id_status,$params)
    {
        $this->db->where('id_status',$id_status);
        return $this->db->update('status',$params);
    }
    
    /*
     * function to delete status
     */
    function delete_status($id_status)
    {
        return $this->db->delete('status',array('id_status'=>$id_status));
    }
}
