<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_unitkerja extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    /*
     * Get unitkerja by id_unitKerja
     */
    public function get_unitkerja($id_unitKerja)
    {
        return $this->db->get_where('unitkerja', array('id_unitKerja'=>$id_unitKerja))->row_array();
    }

    /*
     * Get all unitkerja count
     */
    public function get_all_unitkerja_count()
    {
        $this->db->from('unitkerja');
        return $this->db->count_all_results();
    }

    public function get_unitkerja_all()
    {
        $this->db->order_by('id_unitKerja', 'desc');
        return $this->db->get('unitkerja');
    }

    /*
     * Get all unitkerja
     */
    public function get_all_unitkerja()
    {
        $this->db->order_by('id_unitKerja', 'desc');
        return $this->db->get('unitkerja')->result_array();
    }

    /*
     * function to add new unitkerja
     */
    public function add_unitkerja($params)
    {
        $this->db->insert('unitkerja', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update unitkerja
     */
    public function update_unitkerja($id_unitKerja, $params)
    {
        $this->db->where('id_unitKerja', $id_unitKerja);
        return $this->db->update('unitkerja', $params);
    }

    /*
     * function to delete unitkerja
     */
    public function delete_unitkerja($id_unitKerja)
    {
        return $this->db->delete('unitkerja', array('id_unitKerja'=>$id_unitKerja));
    }
}
