<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_user extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
    }

    /*
     * Get user by id_user
     */
    public function get_user($id_user)
    {
        return $this->db->get_where('user', array('id_user'=>$id_user))->row_array();
    }

    public function get_all_nonteknisi()
    {
        $this->db->select('us.id_user, us.username');
        $this->db->from('user us');
        $this->db->join('notifpengajjuan n', 'us.id_user = n.id_notif', 'left');
        $this->db->where('n.id_user is null');
        $this->db->where(' us.id_user != 1');
    }

    // public function get_jumNotif_ByUser($id_user)
    // {
    //     // $this->db->Select('count(*) as Jumlah');
    //     // $this->db->from('notifpengajuan');
    //     // $this->db->where('id_user', $id_user);
    //     // $this->db->where('StatusNotif', 'No');
    //     // return $this->db->get()->result_array();
    //
    //     $this->db->from('notifpengajuan');
    //     $this->db->where('id_user', $id_user);
    //     $this->db->where('StatusNotif', 'No');
    //     return $this->db->count_all_results();
    // }

    /*
     * Get all user
     */
    public function get_all_user()
    {
        $this->db->order_by('id_user', 'desc');
        return $this->db->get('user')->result_array();
    }
    public function get_user_exadmin()
    {
        $this->db->order_by('id_user', 'desc');
        $this->db->where("id_user != 1");
        return $this->db->get('user')->result_array();
    }
    // public function get_user_all()
    // {
    //     $this->db->order_by('id_user', 'desc');
    //     return $this->db->get('user')->result_array();
    // }

    /*
     * function to login user
     */
    public function Login($login)
    {
        $condition = "USERNAME =" . "'" . $login['USERNAME'] . "' AND " . "PASSWORD =" . "'" . $login['PASSWORD'] . "'";
        $this->db->select('*');
        $this->db->from('user');
        $this->db->where($condition);
        $this->db->limit(1);
        $query = $this->db->get();

        if ($query->num_rows() == 1) {
            return true;
        } else {
            return false;
        }
    }

    public function read_user_information($username)
    {
        $condition = "USERNAME =" . "'" . $username . "'";
        $this->db->select('*');
        $this->db->from('user');
        $this->db->where($condition);
        $this->db->limit(1);
        $query = $this->db->get();

        if ($query->num_rows() == 1) {
            return $query->result();
        } else {
            return false;
        }
    }

    /*
     * function to add new user
     */
    public function add_user($params)
    {
        $this->db->insert('user', $params);
        return $this->db->insert_id();
    }

    public function update_user($id_user, $params)
    {
        $this->db->where('id_user', $id_user);
        return $this->db->update('user', $params);
    }


    public function delete_user($id_user)
    {
        return $this->db->delete('user', array('id_user'=>$id_user));
    }
}
